### ISSUE TITLE
Minimum Py version

### ISSUE THREAD

**Issue by tbeu** [LiquidFun/aoc_tiles#7]
Does not work with Python < 3.11 due to missing datetime.UTC, especially not with Python 3.8 as specified in the pyproject.toml.

For example, Python 3.10.8
```
>>> import datetime
>>> datetime.datetime.now(datetime.UTC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'datetime' has no attribute 'UTC'
```

**Comment by LiquidFun** [comment]
Thanks for letting me know. Not sure how that slipped. Should be fixed in 0.6.1. Let me know if you have other issues.
